
import { jsPDF } from "jspdf";
import { MedicalReport } from "../types";

export const exportReportToPDF = (report: MedicalReport) => {
  const doc = new jsPDF();
  const data = report.analysisData;
  if (!data) return;

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("AI Health Insights - Clinical Summary", 20, 25);
  
  // Meta
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);
  doc.text(`Patient Record ID: ${report.id.slice(0, 8)}`, 20, 50);
  doc.text(`Analysis Date: ${new Date(report.createdAt).toLocaleString()}`, 20, 55);
  doc.text(`File: ${report.fileName}`, 20, 60);

  // Summary
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text("Clinical Summary", 20, 75);
  doc.setFontSize(11);
  const splitSummary = doc.splitTextToSize(data.summary, 170);
  doc.text(splitSummary, 20, 82);

  // Markers Table
  let yPos = 82 + (splitSummary.length * 6) + 10;
  doc.setFontSize(14);
  doc.text("Vital Markers", 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.text("Marker Name", 20, yPos);
  doc.text("Value", 90, yPos);
  doc.text("Ref Range", 130, yPos);
  doc.text("Status", 170, yPos);
  
  doc.setDrawColor(200, 200, 200);
  doc.line(20, yPos + 2, 190, yPos + 2);
  yPos += 10;

  data.vital_markers.forEach((m) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(m.name, 20, yPos);
    doc.text(`${m.value} ${m.unit || ''}`, 90, yPos);
    doc.text(m.range, 130, yPos);
    doc.text(m.status.toUpperCase(), 170, yPos);
    yPos += 8;
  });

  // Urgency
  yPos += 10;
  doc.setFontSize(12);
  doc.text(`Recommended Action Urgency: ${data.urgency_level.toUpperCase()}`, 20, yPos);

  // Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("DISCLAIMER: This analysis is generated by AI and must be reviewed by a licensed doctor.", 20, 285);

  doc.save(`Health_Analysis_${report.id.slice(0, 8)}.pdf`);
};
